version: 1.0.{build}
build_script:
- cmd: |
    echo Setting Version to %appveyor_build_version%
    dotnet restore src/DatabaseTools
    dotnet build src/DatabaseTools /p:Version=%appveyor_build_version%
    dotnet pack src/DatabaseTools /p:Version=%appveyor_build_version%
    dotnet restore test/DatabaseTools.Tests
    dotnet build test/DatabaseTools.Tests
artifacts:
- path: '**/*.nupkg'