version: 1.0.{build}
build_script:
- cmd: |
    dotnet restore src/DatabaseTools
    dotnet build src/DatabaseTools /p:Version=$VERSION
    dotnet pack src/DatabaseTools /p:Version=$VERSION
artifacts:
- path: '**/*.nupkg'
assembly_info:
  patch: true
  assembly_version: '{version}'
  file: '**\AssemblyInfo.cs'