using System;
using System.Collections.Generic;

namespace DatabaseTools
{
    public static class TypeMappings
    {
        public static IList<Tuple<string, string>> MySqlMappings = new [] {
            Tuple.Create("BOOL NOT NULL","bool"),
            Tuple.Create("BOOL NULL","bool?"),
            Tuple.Create("BOOL NULL","boolean?"),
            Tuple.Create("BOOL","bool"),
            Tuple.Create("BOOL","boolean"),
            Tuple.Create("TINYINT NOT NULL","sbyte"),
            Tuple.Create("TINYINT NULL","sbyte?"),
            Tuple.Create("TINYINT UNSIGNED NOT NULL","byte"),
            Tuple.Create("TINYINT UNSIGNED NULL","byte?"),
            Tuple.Create("TINYINT UNSIGNED","byte"),
            Tuple.Create("TINYINT","boolean"),
            Tuple.Create("SMALLINT NOT NULL","short"),
            Tuple.Create("SMALLINT NULL","short?"),
            Tuple.Create("SMALLINT","short"),
            Tuple.Create("SMALLINT UNSIGNED NOT NULL","ushort"),
            Tuple.Create("SMALLINT UNSIGNED NULL","ushort?"),
            Tuple.Create("SMALLINT UNSIGNED","ushort"),
            Tuple.Create("INT NOT NULL","int"),
            Tuple.Create("INT NULL","int?"),
            Tuple.Create("INT","int"),
            Tuple.Create("INT NOT NULL","int32"),
            Tuple.Create("INT NULL","int32?"),
            Tuple.Create("INT","int32"),
            Tuple.Create("INT UNSIGNED NOT NULL","uint"),
            Tuple.Create("INT UNSIGNED NULL","uint?"),
            Tuple.Create("INT UNSIGNED","uint"),
            Tuple.Create("BIGINT NOT NULL","long"),
            Tuple.Create("BIGINT NULL","long?"),
            Tuple.Create("BIGINT","long"),
            Tuple.Create("BIGINT NOT NULL","int64"),
            Tuple.Create("BIGINT NULL","int64?"),
            Tuple.Create("BIGINT","int64"),
            Tuple.Create("BIGINT UNSIGNED NOT NULL","ulong"),
            Tuple.Create("BIGINT UNSIGNED NULL","ulong?"),
            Tuple.Create("BIGINT UNSIGNED","ulong"),
            Tuple.Create("FLOAT NOT NULL","single"),
            Tuple.Create("FLOAT NULL","single?"),
            Tuple.Create("FLOAT","single"),
            Tuple.Create("FLOAT NOT NULL","float"),
            Tuple.Create("FLOAT NULL","float?"),
            Tuple.Create("FLOAT","float"),
            Tuple.Create("DOUBLE NOT NULL","double"),
            Tuple.Create("DOUBLE NULL","double?"),
            Tuple.Create("DOUBLE","double"),
            Tuple.Create("DECIMAL NOT NULL","decimal"),
            Tuple.Create("DECIMAL NULL","decimal?"),
            Tuple.Create("DECIMAL","decimal"),
            Tuple.Create("CHARACTER NOT NULL","	char"),
            Tuple.Create("CHARACTER NULL","char?"),
            Tuple.Create("CHARACTER","char"),
            Tuple.Create("VARCHAR","string"),
            Tuple.Create("MEDIUMTEXT","string"),
            Tuple.Create("DATETIME NOT NULL","datetime"),
            Tuple.Create("DATETIME NULL","datetime?"),
            Tuple.Create("DATETIME","datetime"),
            Tuple.Create("BLOB","byte[]"),
            Tuple.Create("TEXT", "string")
        };

        public static IList<Tuple<string, string>> CSharpMappings = new [] {
            Tuple.Create("Int64","int64"),
            Tuple.Create("Long","long"),
            Tuple.Create("Boolean","boolean"),
            Tuple.Create("Byte[]","byte[]"),
            Tuple.Create("DateTime","datetime"),
            Tuple.Create("Double","double"),
            Tuple.Create("Int32","int"),
            Tuple.Create("Int","int"),
            Tuple.Create("Decimal","decimal"),
            Tuple.Create("Decimal","decimal"),
            Tuple.Create("Single","single"),
            Tuple.Create("Int16","int16"),
            Tuple.Create("Short","short"),
            Tuple.Create("String","string"),
            Tuple.Create("DateTime","datetime"),
            Tuple.Create("DateTime?","datetime?"),
            Tuple.Create("TimeSpan","timespan"),
            Tuple.Create("String","string"),
            Tuple.Create("IPAddress","ipaddress"),
            Tuple.Create("Boolean","boolean"),
            Tuple.Create("Guid","guid"),
            Tuple.Create("Array","array")
        };

        public static IList<Tuple<string, string>> PostGresMappings = new [] {
            Tuple.Create("int8","Int64"),
            Tuple.Create("int8","Long"),
            Tuple.Create("bool","Boolean"),
            Tuple.Create("bytea","Byte[]"),
            Tuple.Create("date","DateTime"),
            Tuple.Create("float8","Double"),
            Tuple.Create("int4","Int32"),
            Tuple.Create("int4","Int"),
            Tuple.Create("money","Decimal"),
            Tuple.Create("numeric","Decimal"),
            Tuple.Create("float4","Single"),
            Tuple.Create("int2","Int16"),
            Tuple.Create("int2","Short"),
            Tuple.Create("text","String"),
            Tuple.Create("time","DateTime"),
            Tuple.Create("timetz","DateTime"),
            Tuple.Create("timestamp","DateTime"),
            Tuple.Create("timestamptz","DateTime"), 
            Tuple.Create("interval","TimeSpan"),
            Tuple.Create("varchar","String"),
            Tuple.Create("inet","IPAddress"),
            Tuple.Create("bit","Boolean"),
            Tuple.Create("uuid","Guid"),
            Tuple.Create("array","Array")
        };
    }
}
